import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/Banner"
import NavBar from "../components/nav/navbar"
// import Card from "../components/card/card"
import Loading from "../components/loading/loading"
import SectionCards from "../components/card/section-cards"
import { getVideos } from "../lib/videos"

export async function getServerSideProps() {
  const disneyVideos = getVideos();
  console.log("check server side props");
  return { props: { disneyVideos } };
}

export default function Home({ disneyVideos }) {
  // const disneyVideos = [
  //   {
  //     imgUrl: "/static/clifford.webp",
  //   },
  //   {
  //     imgUrl: "/static/clifford.webp",
  //   },
  //   {
  //     imgUrl: "/static/clifford.webp",
  //   },
  // ]
  // const disneyVideos = getVideos();
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar username="ayushbhai@bhaibhai.com" />
      <Banner
        title="hi there "
        subTitle="this is some random text"
        imgUrl="/static/clifford.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
      </div>
      <Loading />
    </div>
  )
}
