import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/Banner"
import NavBar from "../components/nav/navbar"
import Card from "../components/card/card"
import Loading from "../components/loading/loading"


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Netflix</h1>

      <NavBar />
      <Banner
        title="hi there "
        subTitle="this is some random text"
        imgUrl="/static/clifford.webp"
      />
      <Card />
      <Loading />


    </div>
  )
}
