import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/Banner"
import NavBar from "../components/nav/navbar"
// import Card from "../components/card/card"
import Loading from "../components/loading/loading"
import SectionCards from "../components/card/section-cards"


export default function Home() {
  const disneyVideos = [
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar username="ayushbhai@bhaibhai.com" />
      <Banner
        title="hi there "
        subTitle="this is some random text"
        imgUrl="/static/clifford.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
      </div>
      <Loading />
    </div>
  )
}
